dashboard_import:
  package_import_url: github://MariuszWoszczynski/WMBUS-reader/WMBUS-reader.yaml@main
  import_full_config: true

substitutions:
  name: "wmbus-reader"
  friendly_name: "wmbus-reader"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader
    version: "1.0"
    
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus ]
    refresh: 0d
    
time:
 - platform: sntp
   id: time_sntp


# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "9p2efbtoh/7izZ93LRVsgSXsL1JAoP07YQeoyATI7IE="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#  static IP configuration (instead of data from the secret file)

#  ssid: "MY_WIFI"
#  password: "0123456789"
#  reboot_timeout: 10min
#  manual_ip:
#    static_ip: 192.168.1.99
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WMBUS Reader - Fallback Hotspot"
    password: "12345678"

captive_portal:

web_serwer: 
  port: 80

wmbus:
  mosi_pin: GPIO32
  clk_pin:  GPIO33 
  miso_pin: GPIO19
  gdo2_pin: GPIO21
  gdo0_pin: GPIO22
  cs_pin:   GPIO23
  log_unknown: true


sensor:
# first sensor (water)
  - platform: wmbus
    meter_id: 0x00000000
    type: izar
    add_prefix: false
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_water_m3:
      name: "My cold water"
   #  filters:              #optional
   #    - offset: 123.4567  #the difference between the indications of the radio overlay and the counter (if you have a used overlay)
    last_month_total_water_m3:
      name: "Last month total water"
    current_month_total_water_l:
      name: "Current month toal water"
    transmit_period_s:
      name: "Transmit period [s]"
    remaining_battery_life_y:
      name: "Remaining battery life [Y]"
    current_alarms:
      name: "Current alarms"
    previous_alarms:
      name: "Previous alarms"
  # second sensor (water)
  - platform: wmbus
    meter_id: 0x00000000
    type: apator162
    add_prefix: false
    key: "00000000000000000000000000000000"
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_water_m3:
      name: "My cold water"
  # third sensor (gas)
  - platform: wmbus
    meter_id: 0x00000000
    type: unismart
    add_prefix: false
    key: "00000000000000000000000000000000"
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_gas_m3:
      name: "My gas"
  # fourth sensor (electricity)
  - platform: wmbus
    meter_id: 0x00000000
    type: amiplus
    add_prefix: false
    mode: T1C1
    rssi:
      name: "My RSSI"
    total_energy_consumption_kwh:
      name: "My consumption in kWh"
      icon: "mdi:power-plug"
    current_power_consumption_kw:
      name: "My current power consumption in kW"
    total_energy_production_kwh:
      name: "My total energy production in kWh"
    current_power_production_kw:
      name: "My current power production in kW"
    voltage_at_phase_1_v:
      name: "My V1"
    voltage_at_phase_2_v:
      name: "My V2"
    voltage_at_phase_3_v:
      name: "My V3"
  # more options on https://github.com/SzczepanLeon/esphome-components
