dashboard_import:
  package_import_url: github://MariuszWoszczynski/WMBUS-reader/WMBUS-reader-v4.yaml@main
  import_full_config: true

substitutions:
  name: "wmbus-reader-v4"
  friendly_name: "WMBUS Reader V4"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader
    version: "1.0"
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus ]
    refresh: 0d

# Status LED for connection
status_led:
  pin:
    # Blue LED
    number: GPIO02
    
mdns:
  disabled: false
  
time:
 - platform: sntp
   id: time_sntp


# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "IAHzf/W7ltjO0oJPBxXC0k7YCXPKRpLmLU4lOnizC9Q="

ota:
  - platform: esphome
    password: "2732cd0e5a1bc7beb2d19537dd821c79"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 18dB
#  static IP configuration (instead of data from the secret file)
#  manual_ip:
#    static_ip: 192.168.10.99
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wmbus-Reader-V4 Fallback Hotspot"

#your mqtt parameters
#mqtt:
#  broker: 10.10.10.10  
#  port: 1883
#  username: username 
#  password: password 

captive_portal:

web_server: 
  port: 80
  version: 3

wmbus:
  mosi_pin: GPIO32
  clk_pin:  GPIO33 
  miso_pin: GPIO19
  gdo2_pin: GPIO21
  gdo0_pin: GPIO22
  cs_pin:   GPIO23

  frequency: 868.950
  all_drivers: False
  sync_mode: True
  log_all: True

#  mqtt:
#    broker: 192.168.XX.XX
#    username: xxxxxxxx
#    password: xxxxxxxx

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    
###########################################################################################################################################################
###########################################################################################################################################################
# The following sensors are examples, for IZAR, APATOR and UNISMART meters. Leave only the configuration of such meters you have, delete the other sensors. 
# If you have another meter, check its configuration on:  https://github.com/SzczepanLeon/esphome-components
###########################################################################################################################################################
###########################################################################################################################################################


# IZAR water meter
  - platform: wmbus
    meter_id: 0x00000000   ######## enter your IZAR meter ID here ###########
    type: izar
    sensors:
      - name: "RSSI IZAR"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "IZAR water meter stater"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"
      - name: "IZAR Consumption in the last month"
        field: "last_month_total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"
      - name: "IZAR Transmission period"
        field: "transmit_period"
        accuracy_decimals: 0
        unit_of_measurement: "Second"
      - name: "IZAR Remaining battery life"
        field: "remaining_battery_life"
        accuracy_decimals: 0
        unit_of_measurement: "Year"

# APATOR 16-2 water meter
  - platform: wmbus
    meter_id: 0x00000000     ######## enter your APATOR meter ID here ###########
    type: apator162
    key: "00000000000000000000000000000000"
    sensors:
      - name: "RSSI APATOR"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "APATOR water meter state"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "water"
        state_class: "total_increasing"
        icon: "mdi:water"

# UNISMART gas meter
  - platform: wmbus
    meter_id: 0x00000000        ######## enter your UNISMART meter ID here ###########
    type: unismart
    key: "00000000000000000000000000000000"
    sensors:
      - name: "RSSI UNISMART"
        field: "rssi"
        accuracy_decimals: 0
        unit_of_measurement: "dBm"
        device_class: "signal_strength"
        state_class: "measurement"
        entity_category: "diagnostic"
      - name: "UNISMART gas meter state"
        field: "total"
        accuracy_decimals: 3
        unit_of_measurement: "m続"
        device_class: "gas"
        state_class: "total_increasing"
        icon: "mdi:water"
        #filters:       #optional    
        #  - offset: 991.10   


